language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
xcode_workspace: UsbSshPlugin.xcodeproj
xcode_scheme: UsbSshPlugin
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
